Project/urls.py

from django.contrib import admin
from django.urls import path,re_path,include
from student import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # re_path(r'^$', views.home, name="home"),
    # re_path(r'^upload/$', views.upload, name="upload"),
    re_path(r'^accounts/',include('accounts.urls')),
    re_path(r'^',include('student.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path,re_path,include
from . import views

app_name = 'accounts'

urlpatterns = [
    re_path(r'^login/$', views.login_view, name="login"),
    re_path(r'^logout/$', views.logout_view, name="logout"),
]

student/urls.py

from django.contrib import admin
from django.urls import path,re_path,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

app_name = 'student'

urlpatterns = [

    re_path(r'^upload/$', views.upload, name="upload"),
    re_path(r'^sms/$', views.send, name="sms"),
    re_path(r'^$',views.home, name="home"),
]


accounts/models.py
from django.db import models

# Create your models here.

student/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User


class Student(models.Model):
    id = models.CharField(max_length=100,primary_key=True)
    name = models.CharField(max_length=100,blank=True,null=True)
    mentor = models.CharField(max_length=100,default='sejal thakkar',blank=True,null=True)
    number = models.IntegerField(blank=True,null=True,default=8154057515)
    father = models.IntegerField(blank=True,null=True,default=8140516739)
    mother = models.IntegerField(blank=True,null=True,default=7984426396)

    def __str__(self):
        return self.id


# class Attendance(models.Model):
#     id = models.ForeignKey(Student, on_delete=models.CASCADE, blank=True, null=True)
#
#     def __str__(self):
#         return self.id


accounts/views.py
from django.shortcuts import render ,redirect
from django.contrib.auth import logout , login
from  django.contrib.auth.forms import AuthenticationForm

# def signup_view(request):
#     if request.method == 'POST':
#         form = SignupForm(request.POST)
#         if form.is_valid():
#             user = form.save()
#             login(request,user)
#             return redirect('home')
#     else:
#         form = SignupForm()
#     return render(request,'accounts/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('student:home')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form': form})


def logout_view(request):
    logout(request)
    return redirect('student:home')



student/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from .models import Student
#for django-excel
from django.shortcuts import render_to_response
from django.http import HttpResponseBadRequest
from django import forms
from django.template import RequestContext
import django_excel as excel
###############################################
import openpyxl
import time
from time import sleep
# from sinchsms import SinchSMS
from twilio.rest import Client


def home(request):
    return render(request,'homepage.html',{})


class UploadFileForm(forms.Form):
    file = forms.FileField()


def upload(request):
    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            filehandle = request.FILES['file']
            filehandle.save_to_database(
                model=Student,
                mapdict=['name', 'mentor', 'id','number','father','mother'])
            return redirect('student:home')
    else:
        form = UploadFileForm()
    return render(request,'upload_form.html', {'form': form})


def send(request):
    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            filehandle = request.FILES['file']

            wb = openpyxl.load_workbook(filehandle)
            worksheet = wb["THEORY"]
            print(worksheet)
            i = 4
            while i < 15:
                temp = str(worksheet[i][0].value)
                i = i + 1
                if temp == "None":
                    break
            j = 4
            t1 = str(worksheet[2][4].value)
            print(t1)
            while j < i - 1:
                enroll = str(worksheet[j][0].value)
                print(enroll)
                std = Student.objects.get(id=enroll)
                number = std.number
                fatherNo = std.father
                motherNo = std.mother
                print(number,fatherNo,motherNo)

                sub1 = str(worksheet[2][2].value)
                sub1Total = str(worksheet[j][2].value)
                sub1Attended = str(worksheet[j][3].value)

                # sub2
                sub2 = str(worksheet[2][5].value)
                sub2Total = str(worksheet[j][5].value)
                sub2Attended = str(worksheet[j][6].value)

                # sub3
                sub3 = str(worksheet[2][8].value)
                sub3Total = str(worksheet[j][8].value)
                sub3Attended = str(worksheet[j][9].value)

                # sub4
                sub4 = str(worksheet[2][11].value)
                sub4Total = str(worksheet[j][11].value)
                sub4Attended = str(worksheet[j][12].value)

                # sub5
                sub5 = str(worksheet[2][14].value)
                sub5Total = str(worksheet[j][14].value)
                sub5Attended = str(worksheet[j][15].value)

                # sub6
                sub6 = str(worksheet[2][17].value)
                sub6Total = str(worksheet[j][17].value)
                sub6Attended = str(worksheet[j][18].value)
                print(str(worksheet[j][1].value), "\n", sub1, sub1Attended, " of ", sub1Total, "\n", sub2, sub2Attended,
                      " of ", sub2Total, "\n", sub3, sub3Attended, " of ", sub3Total, "\n", sub4, sub4Attended, " of ",
                      sub4Total, "\n", sub5, sub5Attended, " of ", sub5Total, "\n", sub6, sub6Attended, " of ",
                      sub6Total, "\n")
                j = j + 1

           # sendSMS()
            return redirect('student:home')
    else:
        form = UploadFileForm()
    return render(request,'send_sms.html', {'form': form})


def sendSMS():
    account_sid = 'AC19b68ab50ce8b6d381aa894b97f00ab1'
    auth_token = '82933ed4e3aa3a72d6b13b2afb0176cf'
    client = Client(account_sid, auth_token)

    message = client.messages \
        .create(
            body="Join Earth's mightiest heroes. Like Kevin Bacon.",
            from_='+13342923372',
            to='+917984426396'
            )
    print(message.sid)

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}
{% load static from staticfiles %}
{% block title %}
Login Page
{% endblock %}
{% block content %}
<h1>this is Login Page</h1>
<form action="/accounts/login/" method="post">
 {% csrf_token %}
 {{ form }}
 <input type="hidden" value="{{ request.GET.next }}">
 <input type="submit" value="Login">
</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}
{% load static from staticfiles %}
{% block title %}
SignUp Page
{% endblock %}
{% block content %}
<h1>This is Signup Page</h1>
<form action="/accounts/signup/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="SignUp">
</form>
{% endblock %}

student/templates/homepage.html
{% extends 'base_layout.html' %}
{% block title %}
Home
{% endblock %}
{% block content %}
    <h1>this is home page</h1>
    <h3>Currently login : {{ user.email }}</h3>
{% endblock %}

student/templates/send_sms.html
{% extends 'base_layout.html' %}
{% block title %}
Upload
{% endblock %}
{% block content %}
    <h1>this is Send SMS page</h1>
    <h3>Currently login : {{ user.email }}</h3>
    <form action="{% url 'student:sms' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

student/templates/upload_form.html
{% extends 'base_layout.html' %}
{% block title %}
Upload
{% endblock %}
{% block content %}
    <h1>this is upload page</h1>
    <h3>Currently login : {{ user.email }}</h3>
    <form action="{% url 'student:upload' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

templates/base_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Lobster|Open+Sans" rel="stylesheet">
  <link rel="stylesheet" href="/static/stylesheet.css">
</head>
<body>
<div class="header-top">
<nav class="navbar navbar-expand-sm bg-success navbar-dark">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Vibes</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'student:home' %}">Home</a></li>
      {% if user.is_authenticated %}
      <li><a href="{% url 'student:upload' %}">Add Student</a></li>
      <li><a href="{% url 'student:sms' %}">Send SMS</a></li>
      {% endif %}
    </ul>
    <ul class="nav navbar-nav navbar-right">

      {% if user.is_authenticated %}
      <li> <form action="{% url 'accounts:logout' %}" method="post">
        {% csrf_token %}
        <span class="glyphicon glyphicon-log-out"></span>
        <input type="submit" value="Logout" class="logout">
      </form> </li>
      <!--<li><a href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>-->
      {% else %}
      <li><a href="' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="{% url 'accounts:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      {% endif %}

    </ul>
  </div>
</nav></div>

<div class="wrapper">
    {% block content %}

    {% endblock %}
</div>

</body>
</html>